title: Nishith's Tech blog
first_name: Nishith
last_name: Sharma
description: "This is my personal Tech blog"
logo_img: "/assets/img/favicon.webp"
profile_img: "/assets/img/shared image.jpg"

# Social Links
email: example@gmail.com
github_username: nitz0301
twitter_username: twitter
instagram_username: instagram
linkedin_username: nishith-sharma0301
facebook_username: facebook

# External API
giscus_repo: "nitz0301/nitz0301.github.io"
giscus_repoid: "R_kgDOPgnA_A"
giscus_category: "Q&A"
giscus_categoryid: "DIC_kwDOPgnA_M4CuWOx"
goatcounter_code: nitz0301
google_analytics:

# If your repo name follows the format "<user-name>.github.io", then leave the below blank.
# Otherwise, set its value as "/<repo-name>". ex) baseurl: /myblog
baseurl:

# Build settings
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-loading-lazy

exclude:
  - docs/

collections:
  pages:
    output: true
    permalink: /:path.html

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
      date: "1900-01-01"

# Markdown newline activator 
kramdown:
  input: GFM
  hard_wrap: true
